### ISSUE TITLE
Vanadium browser

### ISSUE THREAD

**Issue by w9925** [privacytests/privacytests.org#147] opened 2022-12-05 22:27 UTC
Please add the Vanadium browser by GrapheneOS

**Comment by Thorin-Oakenpants** [comment] 2022-12-15 00:10
duplicate of https://github.com/arthuredelstein/privacytests.org/issues/66#issuecomment-1012531114

**Comment by inson1** [comment] 2023-10-30 10:53
Why it isnt closed if its duplicate?

**Comment by arthuredelstein** [comment] 2023-11-14 21:20
Hi @w9925 -- I'm currently not adding browsers, but Vanadium is high on my list for the future. Please see #66.

**Closed by arthuredelstein** 2023-11-14 21:20 UTC
